name: Bulid, test, package and deploy

on:
  push:
    branches:
      - '**'
      - '!master'
    tags-ignore:
      - '*.*.*'

env:
  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

jobs:
  test:
    name: Build ðŸ—ï¸ and test ðŸ§ª
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set JDK to 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Download and cache dependencies
        run: wget  https://arx.deidentifier.org/?ddownload=1924 -O libarx-3.8.0.jar
      - name: Maven install libarx as local dependency
        run: mvn -q install:install-file -Dfile=libarx-3.8.0.jar -DgroupId=org.deidentifier -DartifactId=libarx -Dversion=3.8.0 -Dpackaging=jar
      - name: Prepare code climate test reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Resolve dependencies, plugins, reports
        run: mvn dependency:go-offline
      - name: Create and store version tag
        run: |
          TIME=$(TZ="Europe/Oslo" date +%Y.%m.%d-%H.%M)
          COMMIT=$(git rev-parse --short=12 HEAD)
          VERSION="$TIME-$COMMIT"
          echo "version $VERSION"
          echo $VERSION > docker_img_tag.txt
      - name: Set version in pom
        run: |
          mvn versions:set -DnewVersion="$(cat docker_img_tag.txt)"
          mvn versions:commit
      - name: Run test ðŸ§ª
        run: mvn test
        env:
          CI: true
      - name: Run code climate test reporter and upload
        run: |
          JACOCO_SOURCE_PATH=src/main/java ./cc-test-reporter format-coverage -d ./target/site/jacoco/jacoco.xml --input-type jacoco
          ./cc-test-reporter upload-coverage -d